const loginRoute = '/login/';
const registerRoute = '/register/';
const profileScreen = 'profile_screen';
const verifyEmailRoute = '/verify-email/';
const editProfle = '/edit_profile';
const navigator = '/navigator';
const changePassword = '/change_password';
        // '/': (context) => const LoginView(),
        // '/mainmenu': (context) => const MainMenu(),
        // '/profile_screen': (context) => const ProfileScreen(),
        // '/navigator': (context) => const MenuPrincipal(),
