name: fractoliotesting
description: A new Flutter project.
publish_to: 'none'
version: 0.1.0

environment:
  sdk: '>=2.19.6 <3.0.0'

dependencies:
  camera: ^0.10.5
  cloud_firestore: ^4.8.5
  connectivity_plus: ^4.0.2
  firebase_auth: ^4.5.0
  firebase_core: ^2.11.0

  firebase_storage: ^11.2.6
  flutter:
    sdk: flutter
  flutter_riverpod: ^1.0.1
  image_picker: ^1.0.2
  mobile_scanner: ^3.4.1
  permission_handler: ^10.2.0
  riverpod: ^1.0.1
  string_capitalize: ^0.0.10

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.3
  test: ^1.24.3

flutter:
  uses-material-design: true
