name: fractoliotesting
description: A new Flutter project.
publish_to: 'none'
version: 0.1.0

environment:
  sdk: '>=2.19.6 <3.0.0'

dependencies:
  camera: ^0.10.5
  cloud_firestore: ^4.8.5
  firebase_auth: ^4.5.0
  firebase_core: ^2.11.0

  flutter:
    sdk: flutter
  permission_handler: ^10.2.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0

flutter:
  uses-material-design: true
